language: scala
jdk:
- oraclejdk8

script:
- sbt clean compile
- sbt publishSigned
- sbt sonatypeRelease

scala:
- 2.11.8
- 2.12.4

env:
  global:
  - secure: ld0lwu8qg7gS1eG1QSZITJAX05wVQXdsENhnwYUX0GQaGtris4tCwmyFn9gNQUY2hEB8sZNnaf2Ahefdpk+n8OKRyk0N5Z7O6+gjHby8LQ95E3s2NBtDUzx3uh51ump7CPs/nYKjYgw44WZqzzIgz39g5CJ50SNmt6JsMXGJ2uUtOBp8smq/vZM1ftQINm2e39mf921mucX/0/tC4r8JXseoOQdHk+wUEjs8clB1GcqNA/oZ2Z7XXQUPS3QfW2woleSELS3qWHbN17FnOoGrcgk5GIyA/OSpYxEY8101dFyJXOArmnZ7NZ+YG9UFfbOzXp/TmXFSUK2+yGbDs6O0sNSor/UzHcLo3Q7QBPaw4gBbK1ks+MY3gjQdU0u1bl8FHjd0Pf9JMqLsi/PJxej483P8FMFUPjvBMcSwIcM3VNy2nJPOHvAYl2ewLcmiQeuSK6LOce1uZEWt7gktoHHKRRsQ8pC3EA0qvJagvnt1H/4O1SLiep0h9D0ncW1ZJqpLp4egzTOsOMlIp08w4Eos45v/yvxlm1oaVpa7KlWqcvffqOIVeNgFQ12+2R3siYmXJURot6VAZVBNAN99n9VaDxs9Taqe3Ea47/NPGJSk1fT1cFeIGSYmQQjJPhrLGDsIgd2zMfhnSNaLCKAXLmi+LG4gdjKmGqDA/iXW6+EQ1gY=
  - secure: lDvwQT+NtfnC2wV0kqTatl6+NGukZSQzN97rPeNqy7o2sSv/UAoDkPzFP9bc16jRt+aSYSB57TnQREONniSIXfmrlnMgMpRqib0+hcOOTyzJSBQfbqMcaw8jqoLB82pkGhXOZ+Wb6bJe19cBb7PFuzc9ieFldLRvYqggJCunHmx+pJtNrP8den+m1xZQUJ6otAdCyHikkjsLHN9OTLFLpIkkc5RvQTcLTlRUP3DigZNLdh9A/sdMckjepKBIkcS/jH5LL87tl4qrbRyVEkcbDttCQKntA9eoeHKb5hVXz30xLC8m00X4H/SS1P+ZYWDOi2CR2UrORldddy5dNQIKHMxfxM29Kr3zpf3U9PP7RmG7Qo8aVfX+ytUEhW64GTZum83TPIDwhsT6ISuZtEakXR7DnQug2JRF825Vnj7kNdJTvmx8A4V87EjLTTavz4GGVuvvljBslo3P4s44SttaL7Huri8AFKEGKj+UxvygiQixNtnVnAfNuKziHXRCfDiwQNj5Iycpn4++sAqVVrSf7JxJGh9kODwUDG/qEsOFXelsP2azkSNIabSBjI0V7W8zfCgSPkv9yMKSTq1u3ZXTl2Vs+2IKOhUzN8xZzPlP0AJ1irAmlgZ3XkXatbIHRoklKh+/zfLwgegCyuoMVXbny42e+088ar7xgZEzuPBTuzw=
  - secure: E0PURp4lSaEx2i3ZfaGCqJAHhoIdKhsgwotL8XvpV0r2/qFFFh1QNkhoDB0r17LdZ5jd6f+mSYFuJyaN1oZBmGTRxSo3XLjb0b2tIm/tJrb4XL1PvNnc0B6XDA0401U+/HfQxI5Y8NJdScLBAo1+zaFWaT3R0SuFFGWv1SzC1jI7E3c6lEK2do2kKBwRyAoyzmAI6QeZ0sVODpWFRI6wIaGsw86JZmYlyHl+tGB90kNL5ZFAd2i+S48fX+c1Bu89J9Qc3vexkpf8efH3T5Ps0xle8uIjKDGlL77xSpfItTiKTjhvP98Ejnvn9DdlPIpFzMaqxE4wAUB+GZJMpKAzhRB+HkCZAlhePhzlFDSx4pJw2Uq5N6B6//ztwtlXGNimn7sKTaL9h/ARPir/KQTM1lgqSW0oIEvB42SarkSsNQzK+bRKLoM9d0QBbyEUTO1NQvdhMyBEWVtkuGre4Dy+pndrMZWegvLkmYQAmGHPe9miiqLJhI5hlJaptQvxRt1xczvh+MYA5keBCrEfvZbSP5otkZF9b5He7jLcIvZJZ9iNf+qe3XHP4yT9/XIW1YSFZ9XsmraW8kkIqrfzQ4SbSgQDuK/Ks5WAxTpDJMEt7qoSvF0rzVX8T9gKSYEla9h1llGcJGHThefuPwdWp+Neb0umadEQBRB0ji/Ejh7/u/4=

notifications:
  email:
  - zgwmike@hotmail.com
